### ISSUE TITLE
Recovering 2-of-3 without one of the keys backup

### ISSUE THREAD

**Issue by got3nks** [bitpay/copay-recovery#129]
One of the keys backup was lost, can the Recovery Tool at https://bitpay.github.io/copay-recovery/ be used with just 2 of the 3 keys (since only 2 signatures are required to send a transaction)?

**Comment by got3nks** [comment]
What is the technical reason all the 3 backups are required even if it's a 2 of 3 setup?

**Comment by matiu** [comment]
In other to derive the wallet's addresses you need to have *all* the public keys. In order to sign a transaction, you only need the required keys.

Copay "export" backups have all the wallet's public keys (yours and all other copayers) and only your private key. You can recover a, eg, 2-of-4 wallet by having 1 Copay "export" backup, and one other mnemonic.  But not with only 2 mnemonics, because you can not know the other 2 public keys, so you can derive the wallet's addresses.


You can read more about it at: https://github.com/bitpay/copay/blob/master/README.md#copay-backups-and-recovery
